### ISSUE TITLE
Resolve ArchivesSpace import errors for Princeton University Library EADs

### ISSUE THREAD

**Issue by jrgriffiniii** [ASpace-Metadata-Standards/ead-examples#4]
During an initial attempt to import the EADs provided from the Princeton University Library (these import attempts utilized the ArchivesSpace installation deployed to http://metadata.lyrtech.org/staff), the following imports failed:

- C0001.EAD.xml
- C0002.EAD.xml

The errors logged for these were the following:
```
Error: #&lt;NoMethodError: undefined method `[]&#39; for nil:NilClass&gt;
```

**Comment by regineheberlein** [comment]
closing because it's been a while and we're several versions on
